import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router";
import { useApi } from "../app/providers";
import type { Dashboard, CaseList } from "../api/models";
import { AsyncRegion } from "../components/AsyncRegion";
export function DashboardPage() {
  const api = useApi(); const summary = useQuery({ queryKey: ["dashboard"], queryFn: () => api.get<Dashboard>("/dashboard") });
  const cases = useQuery({ queryKey: ["cases"], queryFn: () => api.get<CaseList>("/cases") });
  return <><div className="page-heading"><div><p className="eyebrow">YOUR DAILY OVERVIEW</p><h1>Good returns. Better resolutions.</h1><p>One workspace for clear decisions and thoughtful customer care.</p></div><Link className="button primary" to="/orders">Find an order <span>↗</span></Link></div><AsyncRegion query={summary}>{data => <div className="stats">{[["Open cases", data.openCases], ["Awaiting approval", data.pendingProposals], ["Eligibility reviews", data.pendingEligibilityReviews], ["Completed today", data.completedRmasToday]].map(([title, value]) => <Link key={title} to={title === "Open cases" ? "/orders" : "/approvals"} className="stat"><span>{title}</span><strong>{value}</strong><small>Current demo session ↗</small></Link>)}</div>}</AsyncRegion><div className="section-heading"><h2>Recent return cases</h2><Link to="/approvals">View approval queue →</Link></div><AsyncRegion query={cases}>{data => <section className="panel">{data.items.length ? <table><thead><tr><th>Order</th><th>Customer</th><th>Reason</th><th>Status</th><th /></tr></thead><tbody>{data.items.map(item => <tr key={item.caseId}><td>{item.orderNumber}</td><td>{item.customerDisplayName}</td><td>{item.reasonCode.replaceAll("_", " ")}</td><td><span className="badge">{item.status}</span></td><td><Link to={`/cases/${item.caseId}`}>Open case →</Link></td></tr>)}</tbody></table> : <div className="empty"><span className="empty-icon">↩</span><h3>A fresh start for every return.</h3><p>Search ORD-1001 to try a return, or ORD-1002 to explore policy exceptions.</p><Link to="/orders" className="button">Explore demo orders</Link></div>}</section>}</AsyncRegion><section className="guidance"><div><p className="eyebrow">BUILT FOR HUMAN JUDGMENT</p><h2>Helpful agents. You make the final call.</h2><p>Agents can gather facts and prepare proposals. Only you can approve a simulated RMA.</p></div><span className="guidance-symbol" aria-hidden="true">✓</span></section></>;
}
