import { useState, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router";
import { useApi } from "../app/providers";
import { money, label, type OrderDetails, type OrderSearchResult, type EligibilityResult } from "../api/models";
import { AsyncRegion } from "../components/AsyncRegion";
export function OrdersPage() {
  const api = useApi(); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [selected, setSelected] = useState("");
  const results = useQuery({ queryKey: ["orders", query], queryFn: () => api.get<OrderSearchResult>(`/orders?query=${encodeURIComponent(query)}`), enabled: query.length >= 2 });
  const order = useQuery({ queryKey: ["order", selected], queryFn: () => api.get<OrderDetails>(`/orders/${selected}`), enabled: !!selected });
  return <><div className="page-heading"><div><p className="eyebrow">START WITH THE FACTS</p><h1>Find an order</h1><p>Search by order number, customer name or email. Select the right match.</p></div></div><form className="search-bar" onSubmit={e => { e.preventDefault(); setQuery(search.trim()); setSelected(""); }}><label className="sr-only" htmlFor="search">Search orders</label><input id="search" minLength={2} maxLength={120} value={search} onChange={e => setSearch(e.target.value)} placeholder="Try ORD-1001 or Avery" required/><button className="primary">Search</button></form>{query && <AsyncRegion query={results}>{data => <section className="panel results"><p>{data.resultCount} matches · {data.requiresSelection ? "Please choose an order; none is selected automatically." : "Select the order to continue."}</p>{data.orders.map(item => <button className={`order-result ${selected === item.orderId ? "selected" : ""}`} key={item.orderId} onClick={() => setSelected(item.orderId)}><strong>{item.orderNumber}</strong><span>{item.customerDisplayName} · {item.maskedEmail}</span><small>Matched by {label(item.matchedBy)} →</small></button>)}{!data.orders.length && <p className="empty">No matching orders. Try a different search.</p>}</section>}</AsyncRegion>}{selected && <AsyncRegion query={order}>{data => <ReturnForm key={data.orderId} order={data}/>}</AsyncRegion>}</>;
}
export function ReturnForm({ order, caseId }: { order: OrderDetails; caseId?: string }) {
  const api = useApi(), navigate = useNavigate(); const key = useRef(crypto.randomUUID()); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [itemId, setItemId] = useState(""); const item = order.items.find(item => item.orderItemId === itemId);
  return <section className="panel padded"><div className="section-heading"><h2>{order.orderNumber} · Order details</h2><span className="badge">{order.status}</span></div><p>{order.customerDisplayName} · Delivered {order.deliveredAt?.slice(0, 10) ?? "not yet"}</p><form onChange={() => { key.current = crypto.randomUUID(); }} onSubmit={async e => {
    e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setError("");
    try { const result = await api.write<EligibilityResult>("/eligibility-checks", { ...(caseId ? { caseId } : {}), orderId: order.orderId, orderItemId: itemId,
      requestedQuantity: Number(form.get("quantity")), reasonCode: form.get("reason"), conditionCode: form.get("condition"),
      ...(form.get("replacement") ? { replacementVariantId: form.get("replacement") } : {}), storeCreditConsent: form.get("consent") === "on", customerNote: form.get("note") }, key.current);
      navigate(`/cases/${result.caseId}`); if (caseId) window.dispatchEvent(new Event("returns-refresh"));
    } catch (error) { setError(error instanceof Error ? error.message : "Unable to check eligibility."); } finally { setBusy(false); }
  }}><div className="form-grid"><label>Order item<select required value={itemId} onChange={e => setItemId(e.target.value)}><option value="">Choose an item</option>{order.items.map(item => <option key={item.orderItemId} value={item.orderItemId}>{item.productTitle} · {item.variantTitle} · {money(item.unitPriceCents, order.currency)}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min={1} max={item?.remainingReturnableQuantity || 100} defaultValue={1} required/></label><label>Return reason<select name="reason">{["wrong_size", "changed_mind", "damaged", "wrong_item", "not_as_described"].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Item condition<select name="condition">{["opened_unused", "unopened", "used", "damaged"].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label></div>{item && <><p className="hint">{item.remainingReturnableQuantity} returnable · Locked policy {item.policyVersionId}</p><label>Optional exchange variant<select key={item.orderItemId} name="replacement"><option value="">No exchange requested</option>{item.replacementVariants.map(v => <option key={v.id} value={v.id}>{v.sku} · {v.inventoryQuantity} available</option>)}</select></label></>}<label className="checkbox"><input type="checkbox" name="consent"/> Customer explicitly agrees to store credit as an option</label><label>Customer note (untrusted text)<textarea name="note" maxLength={1000} rows={3}/></label>{error && <p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy || !item}>{busy ? "Checking…" : "Check return eligibility"}</button></form></section>;
}
