import type { CaseQueryService } from "../../worker/domain/case-query-service";
import type { ApprovalQueueService } from "../../worker/domain/approval-queue-service";
import type { DashboardService } from "../../worker/domain/dashboard-service";
export type Workspace = Awaited<ReturnType<CaseQueryService["getWorkspace"]>>;
export type CaseList = Awaited<ReturnType<CaseQueryService["list"]>>;
export type Activity = Awaited<ReturnType<CaseQueryService["getActivity"]>>;
export type Queue = Awaited<ReturnType<ApprovalQueueService["list"]>>;
export type Dashboard = Awaited<ReturnType<DashboardService["get"]>>;
export type { OrderDetails } from "../../worker/domain/commerce-adapter";
export type { OrderSearchResult } from "../../worker/domain/order-service";
export type { PolicyVersion } from "../../worker/domain/policy-admin-service";
export type { EligibilityResult } from "../../worker/domain/eligibility-service";
export type { MessageDraft } from "../../worker/domain/message-service";
export const money = (cents: number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(cents / 100);
export const label = (value: string) => value.replaceAll("_", " ");
