import { useState } from "react";
import { useApi } from "../app/providers";
import type { PolicyVersion } from "../api/models";
import { ConfirmDialog } from "./ConfirmDialog";
import { useCommand } from "./useCommand";
import type { PolicyRuleType } from "../../worker/domain/policy/types";
const catalog: readonly PolicyRuleType[] = ["delivery_required", "quantity_limit", "return_window", "category_window", "final_sale", "condition_requirement", "reason_exception", "resolution_allowlist", "return_shipping", "return_required", "store_credit_bonus", "manual_review"];
export function PolicyEditor({ policy, clone = false, onClose }: { policy: PolicyVersion; clone?: boolean; onClose: () => void }) {
  const api = useApi(), command = useCommand(onClose);
  const [rules, setRules] = useState(() => policy.rules.map(r => ({ ...r, id: clone ? crypto.randomUUID() : r.id, conditionsText: JSON.stringify(r.conditions), outcomeText: JSON.stringify(r.outcome) })));
  const [error, setError] = useState("");
  if (!clone && policy.status !== "draft") return <p role="alert">Active and retired policies are immutable.</p>;
  return <ConfirmDialog title={clone ? "Create policy draft" : "Edit policy draft"} onClose={() => { if (!command.busy) onClose(); }}><form onSubmit={async event => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget);
    try {
      const payload = { name: form.get("name"), defaultWindowDays: Number(form.get("window")), absoluteMaxWindowDays: Number(form.get("maxWindow")), defaultReturnRequired: form.get("return") === "on", defaultResolutions: form.getAll("resolutions"), returnShippingPayer: form.get("shipping"),
        rules: rules.map(({ conditionsText, outcomeText, ...rule }) => ({ ...rule, conditions: JSON.parse(conditionsText) as unknown, outcome: JSON.parse(outcomeText) as unknown })), ...(!clone ? { expectedVersion: policy.version } : {}) };
      await command.run(payload, key => api.write(clone ? "/policy-versions" : `/policy-versions/${policy.id}`, payload, key, clone ? "POST" : "PATCH"));
    } catch { setError("Rule conditions and outcomes must be valid JSON objects. No changes saved."); }
  }}><p>Save a draft first, then validate it before activation. Existing orders keep their locked version.</p><label>Policy name<input name="name" required maxLength={120} defaultValue={clone ? `${policy.name} (draft)` : policy.name}/></label><div className="form-grid"><label>Default window (days)<input type="number" name="window" min={0} max={3650} required defaultValue={policy.defaultWindowDays}/></label><label>Absolute maximum (days)<input type="number" name="maxWindow" min={0} max={3650} required defaultValue={policy.absoluteMaxWindowDays}/></label></div><label className="checkbox"><input type="checkbox" name="return" defaultChecked={policy.defaultReturnRequired}/>Return required by default</label><fieldset><legend>Default resolutions</legend>{["refund", "exchange", "store_credit"].map(r => <label className="checkbox" key={r}><input type="checkbox" name="resolutions" value={r} defaultChecked={policy.defaultResolutions.some(v => v === r)}/>{r}</label>)}</fieldset><label>Return shipping payer<select name="shipping" defaultValue={policy.returnShippingPayer}><option value="merchant">Merchant</option><option value="customer">Customer</option></select></label>
    <details><summary>Rule catalog · {rules.length} rules</summary><p className="hint">Conditions: category, finalSale, reasonCodes, conditionCodes, minRefundableAmountCents, maxRefundableAmountCents. Outcomes: eligibility, reasonCode, returnWindowDays, allowedResolutions, returnRequired, returnShippingPayer, storeCreditBonusBps, storeCreditBonusCents. Unknown keys are rejected.</p>
    {rules.map((rule, index) => <fieldset key={rule.id}><legend>Rule {index + 1}</legend><label>Catalog type<select value={rule.ruleType} onChange={e => setRules(rules.map((r, i) => i === index ? { ...r, ruleType: e.target.value as PolicyRuleType } : r))}>{catalog.map(type => <option key={type}>{type}</option>)}</select></label><label>Priority<input type="number" value={rule.priority} onChange={e => setRules(rules.map((r, i) => i === index ? { ...r, priority: Number(e.target.value) } : r))}/></label><label>Explanation<input required maxLength={500} value={rule.explanation} onChange={e => setRules(rules.map((r, i) => i === index ? { ...r, explanation: e.target.value } : r))}/></label>{(["conditionsText", "outcomeText"] as const).map(field => <label key={field}>{field === "conditionsText" ? "Conditions (JSON object)" : "Outcome (JSON object)"}<textarea value={rule[field]} onChange={e => setRules(rules.map((r, i) => i === index ? { ...r, [field]: e.target.value } : r))}/></label>)}<label className="checkbox"><input type="checkbox" checked={rule.active} onChange={e => setRules(rules.map((r, i) => i === index ? { ...r, active: e.target.checked } : r))}/>Active rule</label><button type="button" onClick={() => setRules(rules.filter((_, i) => i !== index))}>Remove rule {index + 1}</button></fieldset>)}<button type="button" disabled={rules.length >= 50} onClick={() => setRules([...rules, { id: crypto.randomUUID(), ruleType: "manual_review", priority: 10, conditions: {}, outcome: {}, explanation: "Human review required", active: true, conditionsText: "{}", outcomeText: '{"eligibility":"needs_review","reasonCode":"MANUAL_REVIEW_REQUIRED"}' }])}>Add catalog rule</button></details>
    {(error || command.error) && <p className="error" role="alert">{error || command.error}</p>}<button className="primary" disabled={command.busy || command.stale}>Save draft</button></form></ConfirmDialog>;
}

export function PolicyActivation({ policy, onClose }: { policy: PolicyVersion; onClose: () => void }) {
  const api = useApi(), command = useCommand(onClose); const [validation, setValidation] = useState<{ valid: boolean; conflicts: readonly { field: string; ruleIds: readonly string[] }[] } | null>(null);
  const [error, setError] = useState("");
  return <ConfirmDialog title="Validate & activate policy" onClose={() => { if (!command.busy) onClose(); }}><p>Activate {policy.name}, version {policy.versionNumber}. The former active version will be retired. Locked orders are unchanged.</p><button onClick={async () => { setValidation(null); setError(""); try { setValidation(await api.write(`/policy-versions/${policy.id}/validate`, {})); } catch (e) { setError(e instanceof Error ? e.message : "Validation failed"); } }}>Validate saved draft</button>{validation && <div role="status"><p>{validation.valid ? "Validation passed. Ready for explicit activation." : "Resolve these conflicts before activation:"}</p>{validation.conflicts.map((c, i) => <p key={i}>{c.field}: {c.ruleIds.join(", ")}</p>)}</div>}{(error || command.error) && <p className="error" role="alert">{error || command.error}</p>}<button className="primary" disabled={!validation?.valid || command.busy || command.stale} onClick={() => { const payload = { expectedVersion: policy.version }; void command.run(payload, key => api.write(`/policy-versions/${policy.id}/activate`, payload, key)); }}>Confirm activation</button></ConfirmDialog>;
}
